// <auto-generated />
using System;
using FlygplatsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlygplatsApi.Migrations
{
    [DbContext(typeof(Flygplatskontext))]
    [Migration("20250625113012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlygplatsApi.Models.Flyg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Ankomst")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Avgang")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Boarding")
                        .HasColumnType("bit");

                    b.Property<string>("Flygbolag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flygnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.ToTable("Flyg");
                });

            modelBuilder.Entity("FlygplatsApi.Models.Gate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terminal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("FlygplatsApi.Models.Flyg", b =>
                {
                    b.HasOne("FlygplatsApi.Models.Gate", "Gate")
                        .WithMany("Flyg")
                        .HasForeignKey("GateId");

                    b.Navigation("Gate");
                });

            modelBuilder.Entity("FlygplatsApi.Models.Gate", b =>
                {
                    b.Navigation("Flyg");
                });
#pragma warning restore 612, 618
        }
    }
}
